### ISSUE TITLE
Issue while running npm install

### ISSUE THREAD

**Issue by regostar** [saadpasta/developerFolio#559]
### Describe the bug

![image](https://user-images.githubusercontent.com/26195098/210129329-5a5c4555-ae77-4018-a200-41644885be16.png)

### Steps to reproduce

Haven't added github token
ran npm install inside developerFolio folder

### Expected behavior

install correctly

### Is this responsiveness Issue

no

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by opeyemibami** [comment]
try with npm install --legacy-peer-deps

**Comment by Arshad9999** [comment]
You can skip the terminal installation, and give a try to installing it from its official website on your Browser.
It works for me when I get these kinds of issue on terminal.

**Comment by Soham-coder** [comment]
I am also having installation issue. It did not happen earlier.

Error message is as below-

**_npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\Admin\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\Admin\AppData\Local\npm-cache\_cacache\tmp\git-clone-81079a74\node_modules\iltorb
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./scripts/install.js || node-gyp rebuild
npm ERR! npm ERR! info install installing standalone, skipping download.
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@7.1.2
npm ERR! npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! npm ERR! gyp info find Python using Python version 3.11.0 found at "C:\Python311\python.exe"
npm ERR! npm ERR! gyp ERR! find VS
npm ERR! npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! npm ERR! gyp ERR! find VS - not found
npm ERR! npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! npm ERR! gyp ERR! find VS 
npm ERR! npm ERR! gyp ERR! find VS **************************************************************
npm ERR! npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! npm ERR! gyp ERR! find VS **************************************************************
npm ERR! npm ERR! gyp ERR! find VS 
npm ERR! npm ERR! gyp ERR! configure error
npm ERR! npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! npm ERR! gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! npm ERR! gyp ERR! cwd C:\Users\Admin\AppData\Local\npm-cache\_cacache\tmp\git-clone-81079a74\node_modules\iltorb
npm ERR! npm ERR! gyp ERR! node -v v18.12.1
npm ERR! npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! npm ERR! gyp ERR! not ok
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-01-23T20_14_14_481Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-01-23T20_14_25_472Z-debug.log_**

**Comment by kingmaster772** [comment]
same here. maybe because of some deprecated dependencies.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-lottie@1.2.3',
npm WARN EBADENGINE   required: { npm: '^3.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global
_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown u
p to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\Administrator\AppData\Local\npm-cache --prefer-offline=false --prefer-onlin
e=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN old lockfile
npm ERR! npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm ERR! npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm ERR! npm WARN old lockfile
```

**Comment by Soham-coder** [comment]
No above issue is resolved. Use 

yarn install && npm run build

**Comment by Soham-coder** [comment]
> I am also having installation issue. It did not happen earlier.
> 
> Error message is as below-
> 
> **_npm ERR! code 1 npm ERR! git dep preparation failed npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\Admin\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit npm ERR! npm WARN using --force Recommended protections disabled. npm ERR! npm ERR! code 1 npm ERR! npm ERR! path C:\Users\Admin\AppData\Local\npm-cache_cacache\tmp\git-clone-81079a74\node_modules\iltorb npm ERR! npm ERR! command failed npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./scripts/install.js || node-gyp rebuild npm ERR! npm ERR! info install installing standalone, skipping download. npm ERR! npm ERR! gyp info it worked if it ends with ok npm ERR! npm ERR! gyp info using node-gyp@7.1.2 npm ERR! npm ERR! gyp info using node@18.12.1 | win32 | x64 npm ERR! npm ERR! gyp info find Python using Python version 3.11.0 found at "C:\Python311\python.exe" npm ERR! npm ERR! gyp ERR! find VS npm ERR! npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config npm ERR! npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt npm ERR! npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details npm ERR! npm ERR! gyp ERR! find VS looking for Visual Studio 2015 npm ERR! npm ERR! gyp ERR! find VS - not found npm ERR! npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8 npm ERR! npm ERR! gyp ERR! find VS npm ERR! npm ERR! gyp ERR! find VS ************************************************************** npm ERR! npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio npm ERR! npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload. npm ERR! npm ERR! gyp ERR! find VS For more information consult the documentation at: npm ERR! npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows npm ERR! npm ERR! gyp ERR! find VS ************************************************************** npm ERR! npm ERR! gyp ERR! find VS npm ERR! npm ERR! gyp ERR! configure error npm ERR! npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use npm ERR! npm ERR! gyp ERR! stack at VisualStudioFinder.fail (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47) npm ERR! npm ERR! gyp ERR! stack at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16 npm ERR! npm ERR! gyp ERR! stack at VisualStudioFinder.findVisualStudio2013 (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14) npm ERR! npm ERR! gyp ERR! stack at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14 npm ERR! npm ERR! gyp ERR! stack at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16 npm ERR! npm ERR! gyp ERR! stack at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7 npm ERR! npm ERR! gyp ERR! stack at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16 npm ERR! npm ERR! gyp ERR! stack at ChildProcess.exithandler (node:child_process:420:5) npm ERR! npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28) npm ERR! npm ERR! gyp ERR! stack at maybeClose (node:internal/child_process:1091:16) npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.22621 npm ERR! npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" npm ERR! npm ERR! gyp ERR! cwd C:\Users\Admin\AppData\Local\npm-cache_cacache\tmp\git-clone-81079a74\node_modules\iltorb npm ERR! npm ERR! gyp ERR! node -v v18.12.1 npm ERR! npm ERR! gyp ERR! node-gyp -v v7.1.2 npm ERR! npm ERR! gyp ERR! not ok npm ERR! npm ERR! npm ERR! A complete log of this run can be found in: npm ERR! npm ERR! C:\Users\Admin\AppData\Local\npm-cache_logs\2023-01-23T20_14_14_481Z-debug.log
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Admin\AppData\Local\npm-cache_logs\2023-01-23T20_14_25_472Z-debug.log_**

No above issue is resolved. Use

yarn install && npm run build

**Comment by kingmaster772** [comment]
> No above issue is resolved. Use 
> 
> yarn install && npm run build

I'm running this solution and cleaning node_modules several time solves my issue. closing for now

**Comment by abdullahnasir4** [comment]
Deleting package-lock.json file solved it for me.

**Comment by ACwolf55** [comment]
@abdullahnasir4 thank you, Deleting package-lock.json file solved it for me as well
