### ISSUE TITLE
Npm start- SyntaxError: Unexpected token ;

### ISSUE THREAD

**Issue by eszabo12** [saadpasta/developerFolio#597]
### Describe the bug

`Fetching profile data for eszabo12
statusCode: 200
saved file to public/profile.json
/home/elle/Repos/web/developerFolio/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/elle/Repos/web/developerFolio/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! developerfolio@0.1.0 start: `node fetch.js && react-scripts start`
npm ERR! Exit status 1`

### Steps to reproduce

I cloned the repo, edited the environment file, and did npm install. I also tried `npm install --legacy-peer-deps`, 'npm ci && npm install', nothing worked. Nodejs is successfully installed on my computer. OS: Ubuntu 20.04. Environment: VSCode.

### Expected behavior

Something definitely not that.

### Is this responsiveness Issue

NO

### Desktop

- OS: Ubuntu 20.04

### Additional context

I cloned the master just a few days ago.

**Comment by sadapasta** [comment]
@eszabo12 can you please send the screenshot in the thread

**Comment by eszabo12** [comment]
![Screenshot from 2023-02-11 22-17-44](https://user-images.githubusercontent.com/44587911/218296249-1097ff5c-09f2-478a-ad6f-da2d4687aed1.png)

**Comment by saadpasta** [comment]
I can't seems to reproduce this on my machine can you tell me your node version

**Comment by eszabo12** [comment]
v10.19.0

**Comment by saadpasta** [comment]
please update your node version to 16.x.x

**Comment by frankcaoyun** [comment]
Hi @saadpasta ,I encounter the same error using the docker image:

`$ docker run -t -p 3000:3000 developerfolio:latest

> developerfolio@0.1.0 start /app
> node fetch.js && react-scripts start

/app/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! developerfolio@0.1.0 start: `node fetch.js && react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the developerfolio@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-04T07_50_38_360Z-debug.log
[ble: exit 1]`

Is it the same reason as above?

**Comment by hiteshwarmehla21** [comment]
I faced the same issue using the latest node version. Had to get it back to 16.XX to work.

**Comment by jamesjiayu** [comment]
I have the same issue when using docker...
